# Use postgres/example user/password credentials
version: "3.1"

services:
  postgres:
    container_name: mirpg
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_USER: mazed
      POSTGRES_PASSWORD: M@zedm80
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - 5432:5432

volumes:
  postgres-db:
    driver: local
